// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-resty/resty/v2"
	"github.com/israelmiranda/go-expert/di/4/httpclients/brasilapi"
	"github.com/israelmiranda/go-expert/di/4/httpclients/viacep"
	"net/http"
)

// Injectors from wire_inject.go:

func BrasilApiClientProvider() *brasilapi.Client {
	client := newRestyClient()
	brasilapiClient := brasilapi.NewClient(client)
	return brasilapiClient
}

func ViaCepApiClientProvider() *viacep.Client {
	client := newHttpClient()
	viacepClient := viacep.NewClient(client)
	return viacepClient
}

// wire_inject.go:

func newRestyClient() *resty.Client {
	return resty.New()
}

func newHttpClient() *http.Client {
	return &http.Client{}
}
