// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_calculator_proto protoreflect.FileDescriptor

const file_calculator_proto_rawDesc = "" +
	"\n" +
	"\x10calculator.proto\x12\x05proto\x1a\tsum.proto\x1a\fprimes.proto2x\n" +
	"\x11CalculatorService\x12,\n" +
	"\x03Sum\x12\x11.proto.SumRequest\x1a\x12.proto.SumResponse\x125\n" +
	"\x06Primes\x12\x13.proto.PrimeRequest\x1a\x14.proto.PrimeResponse0\x01B:Z8github.com/israelmiranda/go-expert/grpc/calculator/protob\x06proto3"

var file_calculator_proto_goTypes = []any{
	(*SumRequest)(nil),    // 0: proto.SumRequest
	(*PrimeRequest)(nil),  // 1: proto.PrimeRequest
	(*SumResponse)(nil),   // 2: proto.SumResponse
	(*PrimeResponse)(nil), // 3: proto.PrimeResponse
}
var file_calculator_proto_depIdxs = []int32{
	0, // 0: proto.CalculatorService.Sum:input_type -> proto.SumRequest
	1, // 1: proto.CalculatorService.Primes:input_type -> proto.PrimeRequest
	2, // 2: proto.CalculatorService.Sum:output_type -> proto.SumResponse
	3, // 3: proto.CalculatorService.Primes:output_type -> proto.PrimeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_calculator_proto_init() }
func file_calculator_proto_init() {
	if File_calculator_proto != nil {
		return
	}
	file_sum_proto_init()
	file_primes_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculator_proto_rawDesc), len(file_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculator_proto_goTypes,
		DependencyIndexes: file_calculator_proto_depIdxs,
	}.Build()
	File_calculator_proto = out.File
	file_calculator_proto_goTypes = nil
	file_calculator_proto_depIdxs = nil
}
