// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/israelmiranda/go-expert/di/3/infra"
	"github.com/israelmiranda/go-expert/di/3/product"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire_inject.go:

func NewGetProductUseCase(db *sql.DB) *product.GetProductUseCase {
	productRepository := infra.NewProductRepository(db)
	getProductUseCase := product.NewGetProductUseCase(productRepository)
	return getProductUseCase
}

func NewSaveProductUseCase(db *sql.DB) *product.SaveProductUseCase {
	productRepository := infra.NewProductRepository(db)
	saveProductUseCase := product.NewSaveProductUseCase(productRepository)
	return saveProductUseCase
}

// wire_inject.go:

var repositoryProvider = wire.NewSet(infra.NewProductRepository)

var getProductSet = wire.NewSet(
	repositoryProvider, wire.Bind(new(product.ProductGetter), new(*infra.ProductRepository)),
)

var saveProductSet = wire.NewSet(
	repositoryProvider, wire.Bind(new(product.ProductSaver), new(*infra.ProductRepository)),
)
