// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/israelmiranda/go-expert/di/2/infra"
	"github.com/israelmiranda/go-expert/di/2/product"
)

import (
	_ "github.com/mattn/go-sqlite3"
)

// Injectors from wire_inject.go:

func NewUseCase(db *sql.DB) *product.ProductUseCase {
	productRepository := infra.NewProductRepository(db)
	productUseCase := product.NewProductUseCase(productRepository)
	return productUseCase
}

// wire_inject.go:

var addRepositories = wire.NewSet(infra.NewProductRepository, wire.Bind(new(product.ProductRepository), new(*infra.ProductRepository)))
